### ISSUE TITLE
Swapping the loaded state on projects while using a solution filter (.slnf) will sometimes hide the loaded project.

### ISSUE THREAD

**Issue by Swepps** [reduckted/ProjectFilter#4]
To replicate:

- Begin with a multi-project solution and create a solution filter for it by right-clicking the solution and clicking 'Save As Solution Filter'
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/a857f55f-a6e9-4a0e-991c-3d1bf9bc8950)

- Open the solution filter in Visual Studio and unload all but the first project. (Note, this happens in other cases as well but this is the simplest method I could think of to reproduce the issue)
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/71bdb4cb-fa96-401e-b9ab-51fbcffb48b9)

- Now filter the projects again, unloading the first project and loading in the second.
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/90dff937-c214-4bf1-b66c-fa5289420620)

- Notice how the newly loaded project has been hidden.
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/6ee64234-a969-4dda-b736-ba7a69a745c5)

- It can be shown again using 'Unhide Folders' from the context menu.
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/5813c533-46b9-402e-a17a-2ea790625891)

As far as I can tell, this only happens when using the Solution filter files. I think they might still be a bit buggy but perhaps you can find a way around this? It's not a major issue, but I do change my loaded project pretty frequently so it would be nice to not have to do 'Unhide folders' each time.

**Comment by reduckted** [comment]
Awesome, thanks for the reproduction steps. I'm able to reproduce it. I'll see if I can work out what's going wrong.

**Comment by reduckted** [comment]
I think I've fixed this in v2.4.1. It should be available on the marketplace shortly.

If you do continue to encounter this bug, then by all means reopen this issue and I'll take another stab at it!

**Comment by Swepps** [comment]
Works like a charm. Thank you very much for fixing that!
