### ISSUE TITLE
Remember Expanded/Collapsed State

### ISSUE THREAD

**Issue by Mike-E-angelo** [reduckted/ProjectFilter#5]
To start, I wanted to thank you for such an amazing extension! This is really super cool and helps out a lot. I have over 150 projects myself and have been looking into a way to reduce the amount of weight in my development environment. Currently I am using this extension now alongside of two SLNFs -- one for services/server, and another for my Blazor Client applications.

One aspect that I have identified here that would really help out, is the expanded/collapsed state of the different nodes when opening the dialog.  Is there a way to remember the last known state?  Currently everything is expanded upon dialog open, and I have an involved hierarchy and have to collapse/pick through my folder structure to load/unload the projects I would like to modify.

Remembering the last view would be very valuable to me, as I could simply check/uncheck from the view as configured from last time.

Thank you for any consideration and thank you again for creating this extension. 🙏

Happy Holidays 🎅⛄❄

**Comment by reduckted** [comment]
Great idea! This is now available in v2.5.0.

**Comment by Mike-E-angelo** [comment]
Wow! Thank you so much @reduckted I can confirm that this is already available and works on my machine!  That is amazing.  Thank you so much for your efforts and also being able to do this through the holiday season. 🙏🙏🙏
